Fix issue with duplicate parsing of Cache-Control header
apache/httpcomponents-client pull request #424
Opened 2023-03-13 22:07 UTC by arturobernalg

This PR fixes a bug where the same Cache-Control [f3f07a3](https://github.com/apache/httpcomponents-client/pull/420) header is parsed twice, leading to incorrect performance issues. The parsing code has been extracted from the calculateFreshnessLifetime method and is now enhanced to include the main cache control directive that the isExplicitlyNonCacheable method uses to make its decision. This makes the decision based on the main cache control directive instead of parsing the header twice.

Additionally, this PR adds a new method parseCacheControlHeader to the CacheControlParser class which parses the Cache-Control header and returns a CacheControl instance. This new method improves the parsing of the Cache-Control header and provides more accurate parsing of the different directives.

This PR also includes some code cleanup and refactoring.

2023-03-14 16:03 UTC, ok2c requested changes
@arturobernalg Two directives: `no-cache` and `private` should not be represented as a boolean as they may have a list of field names as a parameter. For now, if we do not use those parameters fro caching policies we can keep it like that.

2023-03-14 21:56 UTC, arturobernalg commented on httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
> +
@ok2c  
I agree, however, I am open to any help or advice as it has been challenging to fit all the pieces together. Nevertheless, I am determined to find the optimal solution.

2023-03-15 06:07 UTC, arturobernalg commented on httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
> +
> @arturobernalg Oh, man. This looks ugly. There should be a better way of doing the same.

@ok2c what about now?

2023-03-15 18:25 UTC, ok2c commented
Committed as 8ba0b17aebdcc59a43a3785d751e63cddc2c8a58 with some changes to the parsing code.

@arturobernalg The trick was to reverse the parsing flow and make it simple and linear. Fewer lines of code, fewer intermediate garbage as a result. 
I committed by code under your name as going back and forth with each and every line of change would have taken too long. Please take a look at my changes.

And why on earth did you choose to use deprecated `DateUtils` methods in your tests?

2023-03-15 18:25 UTC, closed without merging

2023-03-15 19:13 UTC, arturobernalg commented
> 8ba0b17

Hi @ok2c 
The change look good.
now I'm lost here -->"And why on earth did you choose to use deprecated DateUtils methods in your tests?"

2023-03-15 19:15 UTC, ok2c commented
@arturobernalg 
```
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ httpclient5-cache ---
[INFO] Toolchain in maven-compiler-plugin: JDK[/opt/java-1.8]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 44 source files to /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/target/test-classes
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[920,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[921,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[942,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[943,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[964,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[965,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[986,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
[WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[987,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
```

2023-03-15 19:18 UTC, arturobernalg commented
> @arturobernalg
> 
> ```
> [INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ httpclient5-cache ---
> [INFO] Toolchain in maven-compiler-plugin: JDK[/opt/java-1.8]
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 44 source files to /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/target/test-classes
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[920,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[921,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[942,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[943,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[964,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[965,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[986,54] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> [WARNING] /home/oleg/src/apache.org/httpcomponents/httpclient/httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java:[987,57] [deprecation] formatDate(Date,String) in DateUtils has been deprecated
> ```

damn.
you right.  I'll tackle that later.

TY